---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole standard configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# If true, pihole standalone is installed
# If false, pihole + unbound is installed
standalone: true|false
use_dhcp_server: false # requires standalone to be false

#unbound configuration
MACVLAN_SERVER_IP: "192.168.0.24"
FTLCONF_REPLY_ADDR4: "192.168.0.24"
REV_SERVER: true
REV_SERVER_DOMAIN: "local"
REV_SERVER_TARGET: "192.168.0.1"
REV_SERVER_CIDR: "192.168.0.0/24"
DOMAIN_NAME: "pihole.local"
# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com
