---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole"
    state: directory
    mode: 0755
  become: false

- name: "Copy Pi-hole docker-compose template to Pi. ({{ 'templates/pi-hole-docker-compose.yml.j2' if standalone else 'templates/pi-hole-unbound-dhcp-docker-compose.yml.j2' if use_dhcp_server else 'templates/pi-hole-unbound-docker-compose.yml.j2' }})"
  ansible.builtin.template:
    src: "{{ 'templates/pi-hole-docker-compose.yml.j2' if standalone else 'templates/pi-hole-unbound-dhcp-docker-compose.yml.j2' if use_dhcp_server else 'templates/pi-hole-unbound-docker-compose.yml.j2' }}"
    dest: "{{ config_dir }}/pi-hole/docker-compose.yml"
    mode: '0640'
  become: false

- name: "Set the TTL manually in pihole-FTL.conf"
  copy: 
    content: "BLOCK_TTL=60 {{ '\n' }}" 
    dest: "{{ config_dir }}/pi-hole/etc-pihole/pihole-FTL.conf"
  become: false
  notify: Restart pi-hole  

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
    pull: true
  become: false
